# deoplete
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

# [[plugins]]
# repo = 'fishbullet/deoplete-ruby'
# on_ft = 'ruby'
# 
# [[plugins]]
# repo = 'Shougo/deoplete-rct'
# on_ft = 'ruby'

[[plugins]]
repo = 'uplus/deoplete-solargraph'
on_ft = 'ruby'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
depends = ['vim-hug-neovim-rpc','nvim-yarp']
hook_post_source = '''
  call deoplete#custom#option('smart_case', v:true)
  call deoplete#custom#option('ignore_case', v:false)
'''

[[plugins]]
repo = 'osyo-manga/vim-monster'
hook_source = '''
  let g:monster#completion#backend = 'solargraph'
  let g:monster#completion#solargraph#backend = "async_solargraph_suggest"
  let g:deoplete#sources#omni#input_patterns = {
    \ "ruby" : '[^. *\t]\.\w*\|\h\w*::',
    \}
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_post_source = '''
  call denite#custom#var('file_rec', 'command', ['rg', '-uu', '--files', '--glob', '!.git'])
  call denite#custom#var('grep', 'command', ['rg'])
	call denite#custom#var('grep', 'default_opts', ['-uu', '--vimgrep', '--no-heading'])
	call denite#custom#var('grep', 'recursive_opts', [])
	call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
	call denite#custom#var('grep', 'separator', ['--'])
	call denite#custom#var('grep', 'final_opts', [])

	call denite#custom#map('insert', '<C-a>', '<denite:move_caret_to_head>', 'noremap')
	call denite#custom#map('insert', '<C-j>', '<denite:move_to_next_line>', 'noremap')
	call denite#custom#map('insert', '<C-k>', '<denite:move_to_previous_line>', 'noremap')
	call denite#custom#map('insert', '<C-f>', '<denite:scroll_page_forwards>', 'noremap')
	call denite#custom#map('insert', '<C-b>', '<denite:scroll_page_backwards>', 'noremap')

  call denite#custom#map('insert', '<C-i>', '<denite:do_action:split>')
  call denite#custom#map('insert', '<C-s>', '<denite:do_action:vsplit>')
  call denite#custom#source('grep', 'converters', ['converter/abbr_word'])
'''
hook_add = '''
  nnoremap <C-u><C-p> :<C-u>Denite file_rec -highlight-mode-insert=Search<CR>
  nnoremap <C-u><C-b> :<C-u>Denite buffer<CR>
  nnoremap <C-u><C-r> :<C-u>Denite -resume<CR>
  nnoremap <C-u><C-g> :<C-u>Denite grep -highlight-mode-insert=Search<CR>
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'eruby']

[[plugins]]
repo = 'gabrielelana/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html', 'css']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'


